name: hello-world
'on': workflow_dispatch
jobs:
  my-job: 
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
         echo "This is line 1"
         echo "This is line 2"
         echo "This is line 3"
